{{- if eq (include "scout.shouldDeploy" .) "true" }}
{{- if .Values.rbac.create }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: scout-role
  labels:
    {{- include "scout.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - extensions
      - ""
    resources:
      - nodes
      - namespaces
      - pods
      - replicationcontrollers
      - replicasets
      - services
      - daemonsets
      - deployments
      - events
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
    verbs:
      - get
      - list
      - watch
  - nonResourceURLs:
      - /healthz
      - /healthz/*
    verbs:
      - get
  - apiGroups:
      - security.openshift.io
    verbs:
      - use
    resources:
      - securitycontextconstraints
    resourceNames:
      - {{ template "container.security.name" . }}-scout
{{- end }}
{{- end }}
