{{- if and (eq true .Values.visionOne.admissionController.enabled) (eq true .Values.visionOne.vulnerabilityScanning.enabled) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: admission-controller-role
  labels:
    {{- include "admissionController.labels" . | nindent 4 }}
rules:
- apiGroups:
  - cloudone.trendmicro.com
  resources:
  - workloadimages
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admission-controller-rolebinding
  labels:
    {{- include "admissionController.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admission-controller-role
subjects:
- kind: ServiceAccount
  name: {{ include "admissionController.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
