{{- if or (.Values.cloudOne.clusterRegistrationKey) (eq (include "container.security.isVisionOneEndpoint" .) "true") }}
apiVersion: visionone.trendmicro.com/v1alpha1
kind: Cluster
metadata:
  name: trendmicro-cluster
{{- end}}