{{- if and (eq true .Values.cloudOne.complianceScan.enabled) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "complianceScanJob.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "complianceScanJob.labels" . | nindent 4 }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: compliance-scan-job-role
  labels:
    {{- include "complianceScanJob.labels" $ | nindent 4 }}
rules:
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterrolebindings
  - roles
  - rolebindings
  verbs:
  - list
  - get
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/proxy
  - pods
  - pods/log
  - configmaps
  - serviceaccounts
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - ""
  resources:
  - pods/exec
  - pods
  verbs:
  - create
  - delete
- verbs:
  - use
  apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  resourceNames:
  - {{ template "container.security.name" . }}-compliance-scanner

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: compliance-scan-job-rolebinding
  labels:
    {{- include "complianceScanJob.labels" $ | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "complianceScanJob.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: compliance-scan-job-role
  apiGroup: rbac.authorization.k8s.io
  {{- end }}