{{- if and ( or (eq true .Values.visionOne.runtimeSecurity.enabled) (eq true .Values.visionOne.malwareScanning.enabled)) (eq "tls" .Values.visionOne.k8sMetaCollector.grpcAuth.type) }}

{{- $cn := (include "k8sMetaCollector.svc.url" .) }}
{{- $ca := genCA (printf "%s-ca"  (include "k8sMetaCollector.fullname" .)) (default 3650 (int .Values.visionOne.k8sMetaCollector.grpcAuth.certificate.lifetime)) -}}
{{- $cert := genSignedCert $cn nil (list $cn) (default 3650 (int .Values.visionOne.k8sMetaCollector.grpcAuth.certificate.lifetime)) $ca -}}

---

apiVersion: v1
kind: Secret
metadata:
  name:  {{ template "k8sMetaCollector.fullname" . }}-tls-certificate
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8sMetaCollector.labels" . | nindent 4 }}
type: Opaque
data:
  key.pem: {{ $cert.Key | b64enc | quote }}
  cert.pem: {{ $cert.Cert | b64enc | quote }}
  ca-cert.pem: {{ $ca.Cert | b64enc | quote }}

{{- end }}