{{- $cn := printf "%s.%s.svc" "trendmicro-kube-rbac-proxy" .Release.Namespace }}
{{- $ca := genCA (printf "%s-ca" "trendmicro-kube-rbac-proxy") (default 3650 (int .Values.visionOne.kubeRbacProxy.certificate.lifetime)) -}}
{{- $cert := genSignedCert (default $cn .Values.visionOne.kubeRbacProxy.certificate.commonName) (default nil .Values.visionOne.kubeRbacProxy.certificate.ipAlternativeNames) (default (list $cn) .Values.visionOne.kubeRbacProxy.certificate.dnsAlternativeNames) (default 3650 (int .Values.visionOne.kubeRbacProxy.certificate.lifetime)) $ca -}}

apiVersion: v1
kind: Secret
metadata:
  name:  {{ template "kubeRbacProxy.fullname" . }}-tls-certificate
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "container.security.labels" . | nindent 4 }}
type: Opaque
data:
  key.pem: {{ $cert.Key | b64enc | quote }}
  cert.pem: {{ $cert.Cert | b64enc | quote }}
