{{- if eq true .Values.visionOne.oversight.enabled }}
apiVersion: cloudone.trendmicro.com/v1
kind: Oversight
metadata:
  name: {{ template "oversight.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oversight.labels" . | nindent 4 }}
{{- end }}
