apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: policy-operator-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "policyOperator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - watch
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - update
  - create
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: policy-operator-role-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "policyOperator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: policy-operator-role
subjects:
- kind: ServiceAccount
  name: {{ include "policyOperator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
