{{- if eq true .Values.cloudOne.clusterRegistrationKey }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: policy-operator-secret-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "policyOperator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: policy-operator-secret-role-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "policyOperator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: policy-operator-secret-role
subjects:
- kind: ServiceAccount
  name: {{ include "policyOperator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}