apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: policy-operator-cluster-role
  labels:
    {{- include "policyOperator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - visionone.trendmicro.com
  resources:
  - clusterpolicies
  - runtimerulesets
  - clusters
  verbs:
  - get
  - delete
- apiGroups:
  - cloudone.trendmicro.com
  resources:
  - workloadimages
  verbs:
  - get
  - delete
- apiGroups:
  - container-security.trendmicro.com
  resources:
  - clusterpolicies
  - runtimerulesets
  - clusters
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - container-security.trendmicro.com
  resources:
    - clusterpolicies/status
    - runtimerulesets/status
    - clusters/status
    - clusters/finalizers
  verbs:
    - get
    - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
{{- if eq true .Values.visionOne.policyOperator.enableRuntimeMitigation }}
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - patch
  - update
  - delete
{{- end }}
{{- if eq true .Values.visionOne.policyOperator.enableNetworkPolicyCreation }}
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies/status
  verbs:
  - get
  - patch
  - update
{{- end }}
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - delete
  resourceNames:
  - clusters.visionone.trendmicro.com
  - clusterpolicies.visionone.trendmicro.com
  - runtimerulesets.visionone.trendmicro.com
  - workloadimages.cloudone.trendmicro.com
  - usages.cloudone.trendmicro.com
  - oversights.cloudone.trendmicro.com
- apiGroups:
  - container-security.trendmicro.com
  resources:
  - clusters
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: policy-operator-cluster-role-rolebinding
  labels:
    {{- include "policyOperator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: policy-operator-cluster-role
subjects:
- kind: ServiceAccount
  name: {{ include "policyOperator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
