{{- if and (or (eq true .Values.cloudOne.vulnerabilityScanning.enabled) (eq true .Values.cloudOne.malwareScanning.enabled)) .Values.securityContextConstraints.create (.Capabilities.APIVersions.Has "security.openshift.io/v1") }}
{{- $excludedNamespaces := .Values.cloudOne.exclusion.namespaces }}

{{- if .Values.serviceAccount.create }}
{{- range $index, $namespace := (lookup "v1" "Namespace" "" "").items }}
{{- if not (has $namespace.metadata.name $excludedNamespaces) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "scanJob.serviceAccountName" $ }}
  namespace: {{ $namespace.metadata.name | quote }}
  labels:
    {{- include "scanner.labels" $ | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
  {{- with $.Values.serviceAccount.scanJob.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: scan-job-role
  labels:
    {{- include "scanner.labels" . | nindent 4 }}
rules:
- verbs:
  - use
  apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  resourceNames:
  - {{ template "container.security.name" . }}-scanner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scan-job-rolebinding
  labels:
    {{- include "scanner.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scan-job-role
subjects:
  {{- range $index, $namespace := (lookup "v1" "Namespace" "" "").items }}
  {{- if not (has $namespace.metadata.name $excludedNamespaces) }}
  - kind: ServiceAccount
    name: {{ include "scanJob.serviceAccountName" $ }}
    namespace: {{ $namespace.metadata.name | quote }}
  {{- end }}
  {{- end }}
{{- end }}
