{{- if and .Values.securityContextConstraints.create (.Capabilities.APIVersions.Has "security.openshift.io/v1") }}
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  annotations:
    kubernetes.io/description: |
      This SCC provides least-privilege requirement to run the scan job in Openshift.
  name: {{ template "container.security.name" . }}-scanner
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "container.security.labels" . | nindent 4 }}
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: false
allowPrivilegedContainer: false
allowedCapabilities:
{{- toYaml .Values.securityContext.scanner.target.capabilities.add | nindent 2}}
allowedUnsafeSysctls: []
defaultAddCapabilities: []
fsGroup:
  type: MustRunAs
groups: []
priority: 0
readOnlyRootFilesystem: true
requiredDropCapabilities: []
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users: []
volumes:
- configMap
- downwardAPI
- emptyDir
- secret
{{- end }}
