{{- if or (eq true .Values.cloudOne.vulnerabilityScanning.enabled) (eq true .Values.cloudOne.malwareScanning.enabled) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: scan-manager-role
  labels:
    {{- include "scanManager.labels" . | nindent 4 }}
rules:
- apiGroups:
  - cloudone.trendmicro.com
  resources:
  - workloadimages
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - ""
  - batch
  - apps
  resources:
  - pods
  - deployments
  - replicasets
  - daemonsets
  - statefulsets
  - jobs
  - cronjobs
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - create
  - update
  - delete
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - create
- apiGroups: 
  - ""
  resources: 
  - services
  - endpoints
  verbs: 
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scan-manager-rolebinding
  labels:
    {{- include "scanManager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scan-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "scanManager.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scan-manager-secrets-remover-role
  labels:
    {{- include "scanManager.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: hook-succeeded,hook-failed,before-hook-creation
    helm.sh/hook-weight: "-9"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "delete"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scan-manager-secrets-remover-rolebinding
  labels:
    {{- include "scanManager.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: hook-succeeded,hook-failed,before-hook-creation
    helm.sh/hook-weight: "-8"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scan-manager-secrets-remover-role
subjects:
- kind: ServiceAccount
  name: scan-manager-secrets-remover-service-account
  namespace: {{ .Release.Namespace }}
{{- end }}
