{{- if not .Values.spc.enabled }}
apiVersion: cloudone.trendmicro.com/v1
kind: Usage
metadata:
  name: {{ template "usage.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "usage.labels" . | nindent 4 }}
{{- end }}
