{{- if eq true .Values.cloudOne.admissionController.enabled }}
{{- $cn := printf "%s.%s.svc" "trendmicro-admission-controller" .Release.Namespace }}
{{- $ca := genCA (printf "%s-ca" "trendmicro-admission-controller") (default 3650 (int .Values.cloudOne.admissionController.certificate.lifetime)) -}}
{{- $cert := genSignedCert (default $cn .Values.cloudOne.admissionController.certificate.commonName) (default nil .Values.cloudOne.admissionController.certificate.ipAlternativeNames) (default (list $cn) .Values.cloudOne.admissionController.certificate.dnsAlternativeNames) (default 3650 (int .Values.cloudOne.admissionController.certificate.lifetime)) $ca -}}

apiVersion: v1
kind: Secret
metadata:
  name:  {{ template "admissionController.fullname" . }}-tls-certificate
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "admissionController.labels" . | nindent 4 }}
type: Opaque
data:
  key.pem: {{ $cert.Key | b64enc | quote }}
  cert.pem: {{ $cert.Cert | b64enc | quote }}

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "admissionController.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "admissionController.labels" . | nindent 4 }}
webhooks:
  - name: {{ default $cn .Values.cloudOne.admissionController.certificate.commonName }}
    namespaceSelector:
      matchExpressions:
      {{- $excludedNamespaces := (include "namespaceExclusions" .) | splitList "," }}
      {{- if $excludedNamespaces }}
      - key: kubernetes.io/metadata.name
        operator: NotIn
        values:
        {{- range $excludedNamespace := $excludedNamespaces }}
        - {{ quote $excludedNamespace }}
        {{- end }}
      {{- end }}
      {{- range $k, $v := (required "A validationNamespaceSelector is required" .Values.cloudOne.admissionController.validationNamespaceSelector) }}
      {{- range $match := $v }}
      -
      {{- range $key, $val := $match }}
        {{- if eq $key "values" }}
        values:
          {{- range $val }}
          - {{ quote . }}
          {{- end }}
        {{- else }}
        {{ $key }}: {{ quote $val }}
        {{- end }}
      {{- end }}
      {{- end }}
      {{- end }}
    rules:
      - apiGroups:
          - '*'
        apiVersions:
          - '*'
        operations:
          - '*'
        resources:
          - "pods"
          - "pods/exec"
          - "pods/portforward"
          - "pods/attach"
          - "pods/ephemeralcontainers"
          - "replicasets"
          - "replicationcontrollers"
          - "deployments"
          - "statefulsets"
          - "daemonsets"
          - "jobs"
          - "cronjobs"
        scope: "Namespaced"
    failurePolicy: {{ required "A valid failure policy is required!" .Values.cloudOne.admissionController.failurePolicy }}
    clientConfig:
      service:
        name: trendmicro-admission-controller
        namespace: {{ .Release.Namespace }}
        path: "/api/validate"
      caBundle: {{ $ca.Cert | b64enc | quote }}
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    timeoutSeconds: {{ default 30 .Values.cloudOne.admissionController.webhookTimeoutSeconds }}
{{- end }}
